ci: tweaks

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,15 +33,17 @@ after_script:
   - lein annotations
 
 before_deploy:
-  # add version suffix if TAG or create temporary local tag for deployment
-  # so that release from master would not be named untagged-...
+  # Add version suffix if TAG or create temporary local tag for
+  # deployment
   - if [ -n "$TRAVIS_TAG" ]; then
       mv target/raml2http.jar target/raml2http-${TRAVIS-TAG}.jar;
     fi
 
-  # Delete local and remote tags named `latest`
-  - git tag -d latest || true
-  - git push origin :refs/tags/latest || true
+  # Delete local and remote tags named `latest` if they exist
+  # as deploy step wants to create a new tag `latest`and will
+  # fail is unable to do that.
+  #- git tag -d latest || true
+  #- git push origin :refs/tags/latest || true
 
 # Deploy jar file to Github releases
 deploy:
@@ -52,6 +54,7 @@ deploy:
     target_commitish: $TRAVIS_COMMIT
     body: "Binary built from latest commit to master branch."
     file: target/raml2http.jar
+    draft: true
     overwrite: true
     skip_cleanup: true
     on:
